"""Generate PostgreSQL-compatible DDL from NorthStar schema conventions.

Does not execute against any live database. Output is for review / isolated
apply. Business rules stay in application code; PG DDL is structural only.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "database" / "schema.sql"

# SQLite → PostgreSQL type map for generated DDL (TEXT timestamps kept as TEXT
# in Phase 0C so migrated values and app comparisons stay identical).
_TYPE_MAP = (
    (re.compile(r"\bINTEGER PRIMARY KEY AUTOINCREMENT\b", re.I), "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (re.compile(r"\bAUTOINCREMENT\b", re.I), ""),
    (re.compile(r"\bBLOB\b", re.I), "BYTEA"),
    (re.compile(r"\bREAL\b", re.I), "DOUBLE PRECISION"),
)


def _convert_column_line(line: str) -> str:
    text = line
    for pattern, repl in _TYPE_MAP:
        text = pattern.sub(repl, text)
    text = re.sub(
        r"DEFAULT\s*\(\s*datetime\('now'\)\s*\)",
        "DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))",
        text,
        flags=re.I,
    )
    text = re.sub(
        r"DEFAULT\s+datetime\('now'\)",
        "DEFAULT to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')",
        text,
        flags=re.I,
    )
    # SQLite COLLATE NOCASE → rely on LOWER() indexes / citext later.
    text = re.sub(r"\s+COLLATE\s+NOCASE\b", "", text, flags=re.I)
    return text


def _strip_sqlite_only(sql: str) -> str:
    # Remove PRAGMA, FTS virtual tables, and SQLite triggers that call UDFs.
    out_lines: list[str] = []
    skipping_fts = False
    skipping_trigger = False
    for raw in sql.splitlines():
        line = raw.rstrip()
        upper = line.strip().upper()
        if upper.startswith("PRAGMA"):
            continue
        if "CREATE VIRTUAL TABLE" in upper and "FTS" in upper:
            skipping_fts = True
            continue
        if skipping_fts:
            if ";" in line:
                skipping_fts = False
            continue
        if upper.startswith("CREATE TRIGGER"):
            skipping_trigger = True
            continue
        if skipping_trigger:
            # SQLite trigger bodies end with END;
            if upper == "END;" or upper.startswith("END;"):
                skipping_trigger = False
            continue
        out_lines.append(_convert_column_line(line))
    return "\n".join(out_lines)


def render_postgresql_ddl(schema_sql: str | None = None) -> str:
    """Return PostgreSQL DDL derived from schema.sql (or provided SQL text)."""
    source = schema_sql if schema_sql is not None else SCHEMA_PATH.read_text(encoding="utf-8")
    body = _strip_sqlite_only(source)
    header = (
        "-- NorthStar AI PostgreSQL schema (generated, Phase 0C)\n"
        "-- Structural port of database/schema.sql. FTS5 and UDF triggers omitted.\n"
        "-- Apply only to isolated databases. Live SQLite remains authoritative.\n"
        "SET client_encoding = 'UTF8';\n"
        "BEGIN;\n\n"
    )
    footer = (
        "\n\n-- Identity-key / phone-key maintenance: use application upserts\n"
        "-- (crm_identity_keys / contact_phone) or install PG functions separately.\n"
        "-- Search: replace search_fts with tsvector column or dedicated search table.\n"
        "COMMIT;\n"
    )
    # CREATE INDEX IF NOT EXISTS is valid in PG 9.5+.
    body = body.replace("INSERT OR IGNORE", "INSERT")
    return header + body + footer


def sequence_reset_sql(table: str, pk_column: str = "id") -> str:
    """SQL to align a PG identity/sequence after explicit primary-key inserts."""
    seq = f"pg_get_serial_sequence('{table}', '{pk_column}')"
    return (
        f"SELECT setval({seq}, COALESCE((SELECT MAX({pk_column}) FROM {table}), 1), "
        f"true);"
    )
